### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by keller-mark**

### CODE REVIEW

**Comment by keller-mark** [comment]
Looks like this is failing due to files not being available in Google Cloud Platform. I uploaded the 0.0.26 files to AWS but do not have any account or privileges for GCP so someone else may need to upload the files. 

The 0.0.26 files can be accessed in my O2 home dir /home/mk596/research/vitessce-data/big-files/output

**Review by manzt — APPROVED** [review]
Thanks! I think the build is failing because `./test.sh` produces `raster.json` with the new `cloud-target` (which differs from that in `fake-files/output-expected`), so the `url` field is different when comparing with the fixtures. We've previously updated these fixtures by hand to have the new target. I'm not saying this is a great strategy, but since the `raster.json` serves as a manifest of sorts, it must include the GC endpoints.

This does not address your issue of not being able to push to GC, and unfortunately I'm not on O2 (yet) and can't help there. I believe I pinged Nils a while ago and he added me to the GC group, but perhaps @ilan-gold can add you.

Otherwise it looks good, just update the fixtures!

**Review by mccalluc — APPROVED** [review]
If the tests pass, sure... but I haven't worked with this in a while, and originally the tests didn't depend on outside services. Is that no longer true?

I'm also out of the loop: I would have though Google Cloud access was separate from O2... but from Trevor it sounds like the latter is needed to use the former?

**Comment by manzt** [comment]
@mccalluc -- No, I don't believe tests depend on outside services. I think the tests are failing due to the new cloud target version not being reflected in image source urls included the raster fixtures. Mark doesn't have permissions for GCS, but the data he processed is on O2. I think he was asking if someone could push the data from O2 (that has GCS), and I was making the comment I would but don't have access to O2.

**Comment by keller-mark** [comment]
@manzt  are you saying i should also update the value `0.0.24` wherever it appears in the `fake-files` directory? https://github.com/hubmapconsortium/vitessce-data/search?q=0.0.24&unscoped_q=0.0.24

Never mind, I see the last line of your comment now

**Comment by manzt** [comment]
Yes. Hopefully this fixes at least the tests -- sorry for not pointing that out last week when you asked "what do I need to do to release?". I forgot.

Do you still need someone to push to GCS?

**Comment by keller-mark** [comment]
Thanks everyone. @ilan-gold  is helping me, I am pushing the files now. Will try to bring up google cloud account access at the vitessce meeting today

**Pull request merged**
